### ISSUE TITLE
Error occurred when trying to load 'payola-payments'

### ISSUE THREAD

**Issue by NemyaNation** [RailsApps/rails-composer#276]
Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
Rails: Rails 5.1.4
OS: Windows 7

This is the first error of a subsequent of many errors.

Happens when I try create an application using the following settings.
1.),12.),enter,2.),2.),2.),1.),1.)1.),1.),2.),14.),1.)2.),no,no

This happens just after I am asked 
> <r PostgreSQL?(leave blank to use the app name>

I leave it empty and also leave the default socket connection prompt empty and then I type 'y' when asked p? No will abort immediately.

After this 'There was an error trying to load the gem 'payola-payments', after this error a lot of new errors are generated as a cause of this before the console finally terminates the proccess with the error message:

>The template [https://raw.github.com/RailsApps/rails-composer/master/composer.rb
] could not be loaded. Error: The file C:/Users/%USER%/Desktop/Sites/myap
p/app/models/user.rb does not appear to exist

Please help? I just need a simple subscription template and I didn't think it would be this hard just to get it running.

**Comment by DanielKehoe** [comment]
Sorry to hear you got fatigued because of this. Sometimes it happens with open source projects. 

Looks like the payola-payments maintainer merged a fix into the payola-payments master branch on Dec 28, 2017 but did not release a new version of the gem.

I'm going to drop the rails-stripe-membership-saas example application from Rails Composer.
